repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: "data/|.pre-commit-config.yaml"
    -   id: trailing-whitespace
        exclude: "data/|.pre-commit-config.yaml"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7  # Use the latest version available
    hooks:
      - id: ruff
        args: [--fix]
        exclude: "data/|.pre-commit-config.yaml"
      - id: ruff-format  # Enables automatic formatting
        exclude: "data/|.pre-commit-config.yaml"